apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cv-app
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: cv-app
  endpoints:
    - port: metrics
      interval: 15s