apiVersion: v1
kind: Service
metadata:
  name: {{ include "cv-app.fullname" . }}
  labels:
    app: cv-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "cv-app.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - name: metrics
      port: 9117
      targetPort: metrics
